services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=${DB_USER}'
    ports:
      - '${DB_PORT}'
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}'
      - 'RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}'
    ports:
      - '5672'
